### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by jamesa** [Eiriksmal/lawler-dot-io#1]
I came across your site from your post on Hacker News, and really liked the theme of your website.

I was wondering if you would add a License to your project mainly so people know if they can use a theme like the one you've developed for their own sites or not.

Thanks!

**Comment by Eiriksmal** [comment]
Great suggestion, thank you. I didn't think anyone would be interested in the code itself, but I'm pleased to release it under the MIT license.

**Comment by cakiki** [comment]
Sorry to revive an old thread, but since the template is now decoupled from the content, should the license file drop its current header? (https://github.com/Eiriksmal/lawler-dot-io-template/blob/lawler/license.md?plain=1#L1)
